x-common-spiral-variables: &common-spiral-variables
  APP_ENV: ${APP_ENV:-local}
  DEBUG: ${APP_DEBUG:-true}
  TEMPORAL_ADDRESS: ${TEMPORAL_SERVER_HOST}:${TEMPORAL_SERVER_PORT:-7233}
  SENTRY_DSN: ${SENTRY_DSN}
  RR_LOG_LEVEL: ${RR_LOG_LEVEL:-debug}
  RR_APP_LOG_LEVEL: ${RR_APP_LOG_LEVEL:-debug}
  MONOLOG_DEFAULT_CHANNEL: ${MONOLOG_DEFAULT_CHANNEL:-roadrunner}
  MONOLOG_DEFAULT_LEVEL: ${MONOLOG_DEFAULT_LEVEL:-ERROR}
  TOKENIZER_CACHE_TARGETS: ${TOKENIZER_CACHE_TARGETS:-true}
  TEMPORAL_ACTIVITY_WORKERS: ${TEMPORAL_ACTIVITY_WORKERS:-2}
  CYCLE_SCHEMA_CACHE: ${CYCLE_SCHEMA_CACHE:-true}
  HTTP_WORKERS_DEBUG: ${HTTP_WORKERS_DEBUG:-false}
  VELOX_MANIFEST_FILE: ${VELOX_MANIFEST_FILE:-.plugin.yaml}

x-php-service:
  &php
  env_file:
    - .env.app
  environment:
    <<: *common-spiral-variables
  networks:
    - vx-network
  healthcheck:
    test: ""
    disable: true
  restart: always

services:
  vx-app:
    <<: *php
    image: ghcr.io/roadrunner-php/velox-app:latest
    ports:
      - ${VX_HTTP_APP_PORT:-8080}:8080
    environment:
      <<: *common-spiral-variables
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      APP_HOST: ${APP_HOST}

  vx-spa:
    image: ghcr.io/roadrunner-php/velox-spa:latest
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://rr.buggregator.dev}
    ports:
      - ${VX_HTTP_SPA_PORT:-3000}:3000
    networks:
      - vx-network
    restart: always

networks:
  vx-network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.61.0/24