[roadrunner]
ref = "v2025.1.1"

[log]
level = "debug"
mode = "production"

[github]
[github.token]
token = "${GH_TOKEN}"

[github.plugins]
[github.plugins.logger]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "logger"

[github.plugins.server]
ref = "v5.2.9"
owner = "roadrunner-server"
repository = "server"

[github.plugins.rpc]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "rpc"

[github.plugins.lock]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "lock"

[github.plugins.http]
ref = "v5.2.7"
owner = "roadrunner-server"
repository = "http"

[github.plugins.gzip]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "gzip"

[github.plugins.send]
ref = "v5.1.5"
owner = "roadrunner-server"
repository = "send"

[github.plugins.headers]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "headers"

[github.plugins.kv]
ref = "v5.2.8"
owner = "roadrunner-server"
repository = "kv"

[github.plugins.memory]
ref = "v5.2.8"
owner = "roadrunner-server"
repository = "memory"

[github.plugins.metrics]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "metrics"

[github.plugins.status]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "status"

[github.plugins.appLogger]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "app-logger"

[github.plugins.http_metrics]
ref = "1.0.1"
owner = "roadrunner-plugins"
repository = "http-metrics"

[github.plugins.cron]
ref = "main"
owner = "roadrunner-plugins"
repository = "cron"

[github.plugins.velox-middleware]
ref = "main"
owner = "roadrunner-plugins"
repository = "velox-middleware"