name: üì¶ Velox App Docker Image

on:
  release:
    types:
      - created

jobs:
  build-release:
    name: üì¶ Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: üõ†Ô∏è Extract Git metadata (tags, labels) for Docker
        id: service-git
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/roadrunner-php/velox-app
          tags: |
            type=semver,pattern={{version}}

      - name: üì¶ Build Docker Image
        id: docker-service
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          file: ./.docker/php/Dockerfile
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            SERVICE=velox-app
          tags: ${{ steps.service-git.outputs.tags }}
          labels: ${{ steps.service-git.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: üõ†Ô∏è Extract Git metadata for SPA
        id: spa-git
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/roadrunner-php/velox-spa
          tags: |
            type=semver,pattern={{version}}

      - name: üì¶ Build SPA Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          file: ./.docker/spa/Dockerfile
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            SERVICE=velox-spa
          tags: ${{ steps.spa-git.outputs.tags }}
          labels: ${{ steps.spa-git.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
